# Generated by Django 5.2.4 on 2025-07-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uname', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Mail', models.CharField(max_length=50)),
            ],
        ),
    ]
